-- Add expanded role tiers
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'STAFF';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'VENDOR_OWNER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SITE_ADMIN';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPERUSER';
